### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/tileserver#2]
- [ ] Make sure all layers function as expected
- [ ] Make sure proper protocol buffers and pngs are returned
- [ ] Make sure cache is warmed
- [ ] Make sure logging works as expected
- [ ] Validate functioning of caches
- [ ] Validate functioning of headers

**Comment by davenquinn** [comment]
We've now created a basic test-fixture database housed in this repository that we can call on to create tests.
